- name: FETCH_CLIENT1
  hosts: pi
  tasks:
    - fetch: 
        src: /etc/openvpn/easy-rsa/keys/ca.crt
        dest: ca.crt
        flat: yes
      become: true
      become_user: root
    - fetch:
        src: /etc/openvpn/easy-rsa/keys/client1.crt
        dest: client1.crt
        flat: yes
      become: true
      become_user: root
    - fetch:
        src: /etc/openvpn/easy-rsa/keys/client1.key
        dest: client1.key
        flat: yes
      become: true
      become_user: root
    - fetch:
        src: /etc/openvpn/easy-rsa/keys/ta.key
        dest: ta.key
        flat: yes
      become: true
      become_user: root

    