- name: "REMOVE_LOCAL_CLIENT2"
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: "REMOVE_CA_CERT"
    command: rm client.conf
    become: true
    become_user: root
  - name: "REMOVE_CA_CERT"
    command: rm client.ovpn
    become: true
    become_user: root